import type { LucideIcon } from "lucide-react";
import {
  Sunrise,
  Feather,
  Heart,
  Flame,
  Eye,
  Moon,
  HeartPulse,
  Gem,
  RefreshCw,
  Lightbulb,
  Hourglass,
  DoorOpen,
  Users,
  Trophy,
  Compass,
  Waves,
  Smile,
  BookOpen,
  Scale,
  Anchor,
  HandHeart,
  Sprout,
  Sparkles,
  Mountain,
} from "lucide-react";

export type OracleTheme = "violet" | "gold" | "rose" | "teal" | "indigo" | "amber";

export interface OracleCard {
  id: number;
  nameTh: string;
  nameEn: string;
  symbol: LucideIcon;
  keywordTh: string;
  messageTh: string;
  affirmationTh: string;
  theme: OracleTheme;
}

export const ORACLE_CARDS: OracleCard[] = [
  {
    id: 1,
    nameTh: "การเริ่มต้นใหม่",
    nameEn: "New Beginning",
    symbol: Sunrise,
    keywordTh: "เริ่มต้น",
    messageTh: "จักรวาลเปิดหน้าใหม่ให้คุณ หัวใจที่พร้อมจะเริ่มคือพลังที่ยิ่งใหญ่ที่สุดในตอนนี้",
    affirmationTh: "ฉันพร้อมที่จะเริ่มต้นใหม่ด้วยใจที่เปิดกว้าง",
    theme: "gold",
  },
  {
    id: 2,
    nameTh: "การปล่อยวาง",
    nameEn: "Letting Go",
    symbol: Feather,
    keywordTh: "ปล่อยวาง",
    messageTh: "สิ่งที่แบกไว้ไม่ใช่ของขวัญจากจักรวาล — ปล่อยมือจากสิ่งที่หนักใจ แล้วจะเบาและลอยได้เอง",
    affirmationTh: "ฉันปล่อยวางสิ่งที่ไม่ได้เป็นของฉันอย่างสงบ",
    theme: "teal",
  },
  {
    id: 3,
    nameTh: "ความรัก",
    nameEn: "Love",
    symbol: Heart,
    keywordTh: "หัวใจ",
    messageTh: "พลังแห่งความรักกำลังไหลเวียนรอบตัวคุณ เปิดใจรับ และให้ความรักกับตัวเองก่อนเสมอ",
    affirmationTh: "ฉันเปิดใจรับความรักและมอบความรักให้ตัวเอง",
    theme: "rose",
  },
  {
    id: 4,
    nameTh: "ความกล้า",
    nameEn: "Courage",
    symbol: Flame,
    keywordTh: "ความกล้า",
    messageTh: "ไฟในใจคุณยังลุกโชน รอวันที่จะก้าวไปข้างหน้า อย่าให้ความกลัวเป็นตัวตัดสินใจแทนคุณ",
    affirmationTh: "ฉันกล้าที่จะก้าวต่อไปแม้ใจจะสั่น",
    theme: "amber",
  },
  {
    id: 5,
    nameTh: "สัญชาตญาณ",
    nameEn: "Intuition",
    symbol: Eye,
    keywordTh: "เชื่อใจตัวเอง",
    messageTh: "เสียงข้างในที่คุณได้ยินคือคำตอบที่แท้จริง จงฟังมัน มากกว่าสิ่งที่คนอื่นบอกให้เชื่อ",
    affirmationTh: "ฉันฟังและเชื่อในสัญชาตญาณของฉัน",
    theme: "violet",
  },
  {
    id: 6,
    nameTh: "ความสงบ",
    nameEn: "Stillness",
    symbol: Moon,
    keywordTh: "สงบนิ่ง",
    messageTh: "ไม่จำเป็นต้องรีบ ความเงียบในตอนนี้กำลังสอนคุณถึงคุณค่าของการพักและสังเกต",
    affirmationTh: "ฉันสงบนิ่งและไว้วางใจจังหวะของชีวิต",
    theme: "indigo",
  },
  {
    id: 7,
    nameTh: "การเยียวยา",
    nameEn: "Healing",
    symbol: HeartPulse,
    keywordTh: "ฟื้นฟู",
    messageTh: "แผลจะค่อย ๆ ดีขึ้น ใจที่เคยเจ็บกำลังเยียวยาตัวเอง ให้เวลามัน และอย่ารีบฝืน",
    affirmationTh: "ฉันยอมให้ตัวเองหายดีอย่างค่อยเป็นค่อยไป",
    theme: "rose",
  },
  {
    id: 8,
    nameTh: "ความมั่งคั่ง",
    nameEn: "Abundance",
    symbol: Gem,
    keywordTh: "มั่งคั่ง",
    messageTh: "ความอุดมสมบูรณ์มีอยู่รอบตัวคุณ เปิดตาให้เห็นโอกาสที่ซ่อนอยู่ แล้วมันจะไหลเข้ามา",
    affirmationTh: "ฉันเปิดรับความมั่งคั่งในทุกรูปแบบ",
    theme: "gold",
  },
  {
    id: 9,
    nameTh: "การเปลี่ยนแปลง",
    nameEn: "Transformation",
    symbol: RefreshCw,
    keywordTh: "เปลี่ยนผ่าน",
    messageTh: "การเปลี่ยนแปลงทำให้รู้สึกไม่มั่นคง แต่คือทางเดียวที่จะโต — ก้าวผ่านมันด้วยความเชื่อมั่น",
    affirmationTh: "ฉันเติบโตผ่านการเปลี่ยนแปลง",
    theme: "teal",
  },
  {
    id: 10,
    nameTh: "ความชัดเจน",
    nameEn: "Clarity",
    symbol: Lightbulb,
    keywordTh: "กระจ่าง",
    messageTh: "คำตอบที่คุณตามหาจะปรากฏชัดขึ้นเมื่อคุณหยุดวิ่งและมองลึกเข้าไปในตัวเอง",
    affirmationTh: "ฉันเห็นทางของฉันอย่างชัดเจน",
    theme: "amber",
  },
  {
    id: 11,
    nameTh: "ความอดทน",
    nameEn: "Patience",
    symbol: Hourglass,
    keywordTh: "รอคอย",
    messageTh: "ทุกอย่างมีเวลาของมัน อย่าเร่งดอกไม้ให้บาน เชื่อว่าเวลาจะพาคุณไปยังที่ที่ควรไป",
    affirmationTh: "ฉันอดทนและไว้วางใจในเวลาของชีวิต",
    theme: "indigo",
  },
  {
    id: 12,
    nameTh: "โอกาส",
    nameEn: "Opportunity",
    symbol: DoorOpen,
    keywordTh: "ประตูเปิด",
    messageTh: "ประตูบานใหม่กำลังเปิดอยู่ตรงหน้า ความกล้าที่จะไขว่คว้าในวันนี้จะเปลี่ยนเส้นทางของพรุ่งนี้",
    affirmationTh: "ฉันพร้อมก้าวผ่านประตูใหม่",
    theme: "gold",
  },
  {
    id: 13,
    nameTh: "ความสัมพันธ์",
    nameEn: "Connection",
    symbol: Users,
    keywordTh: "ผูกพัน",
    messageTh: "คนรอบตัวกำลังส่งพลังงานถึงกัน มอบความจริงใจ แล้วสายใยจะแข็งแรงขึ้นเอง",
    affirmationTh: "ฉันสร้างความสัมพันธ์ด้วยใจจริง",
    theme: "rose",
  },
  {
    id: 14,
    nameTh: "ความสำเร็จ",
    nameEn: "Success",
    symbol: Trophy,
    keywordTh: "สมหวัง",
    messageTh: "ผลของความพยายามกำลังจะปรากฏ จงภาคภูมิใจในทุกก้าวที่เดินมา",
    affirmationTh: "ฉันสมควรได้รับความสำเร็จ",
    theme: "amber",
  },
  {
    id: 15,
    nameTh: "การเดินทาง",
    nameEn: "Journey",
    symbol: Compass,
    keywordTh: "เส้นทาง",
    messageTh: "เข็มทิศชี้ออกไปไกลกว่าที่คุณเคยไป ลองเลือกเส้นทางที่ใจอยากลอง ไม่ใช่แค่เส้นที่คุ้นเคย",
    affirmationTh: "ฉันเดินตามเส้นทางที่ใจเลือก",
    theme: "teal",
  },
  {
    id: 16,
    nameTh: "ความเงียบ",
    nameEn: "Still Water",
    symbol: Waves,
    keywordTh: "นิ่งรับ",
    messageTh: "หยุดโต้คลื่น แล้วปล่อยให้คลื่นสงบลงเอง บางคำตอบมาเมื่อเราเงียบพอจะได้ยิน",
    affirmationTh: "ฉันนิ่งพอจะได้ยินเสียงของใจ",
    theme: "indigo",
  },
  {
    id: 17,
    nameTh: "ความปิติ",
    nameEn: "Joy",
    symbol: Smile,
    keywordTh: "ยิ้ม",
    messageTh: "ความสุขเล็ก ๆ รออยู่รอบตัว รอยยิ้มวันนี้จะกลายเป็นพลังให้วันข้างหน้า",
    affirmationTh: "ฉันเลือกมองหาความสุขในทุกวัน",
    theme: "gold",
  },
  {
    id: 18,
    nameTh: "การเรียนรู้",
    nameEn: "Learning",
    symbol: BookOpen,
    keywordTh: "เปิดใจเรียนรู้",
    messageTh: "ความอยากรู้คือประตูสู่การเติบโต เปิดใจรับสิ่งใหม่ แล้วโลกจะขยายออกไปอีก",
    affirmationTh: "ฉันเรียนรู้จากทุกประสบการณ์",
    theme: "violet",
  },
  {
    id: 19,
    nameTh: "การตัดสินใจ",
    nameEn: "Decision",
    symbol: Scale,
    keywordTh: "ชั่งใจ",
    messageTh: "มีสองทางรออยู่ สิ่งที่ทำให้ใจสงบกว่าคือคำตอบของคุณ ฟังหัวใจแล้วเลือก",
    affirmationTh: "ฉันเลือกด้วยใจที่สงบ",
    theme: "amber",
  },
  {
    id: 20,
    nameTh: "ความเชื่อมั่น",
    nameEn: "Trust",
    symbol: Anchor,
    keywordTh: "มั่นคง",
    messageTh: "จงมั่นคงเหมือนสมอเรือในใจกลางพายุ ความเชื่อมั่นในตัวเองคือที่พึ่งที่แน่นอนที่สุด",
    affirmationTh: "ฉันมั่นคงและเชื่อมั่นในตัวเอง",
    theme: "indigo",
  },
  {
    id: 21,
    nameTh: "การให้อภัย",
    nameEn: "Forgiveness",
    symbol: HandHeart,
    keywordTh: "ให้อภัย",
    messageTh: "การให้อภัยไม่ใช่การยอมแพ้ แต่คือการปลดปล่อยตัวเองจากสิ่งที่หนักอก จงให้อภัยเพื่อตัวคุณเอง",
    affirmationTh: "ฉันให้อภัยเพื่อปลดปล่อยตัวเอง",
    theme: "rose",
  },
  {
    id: 22,
    nameTh: "การเติบโต",
    nameEn: "Growth",
    symbol: Sprout,
    keywordTh: "งอกงาม",
    messageTh: "ต้นกล้าไม่รีบร้อนแต่ไม่เคยหยุดโต จงเติบโตวันละเล็กน้อยอย่างสม่ำเสมอ",
    affirmationTh: "ฉันเติบโตทุกวันอย่างอ่อนโยน",
    theme: "teal",
  },
  {
    id: 23,
    nameTh: "ความลึกลับ",
    nameEn: "Mystery",
    symbol: Sparkles,
    keywordTh: "ไม่รู้ก็ได้",
    messageTh: "บางสิ่งไม่จำเป็นต้องมีคำตอบในวันนี้ ปล่อยให้ความลึกลับสอนใจ และเก็บความอัศจรรย์ไว้",
    affirmationTh: "ฉันยอมรับสิ่งที่ยังไม่รู้ด้วยใจที่สงบ",
    theme: "violet",
  },
  {
    id: 24,
    nameTh: "ความมุ่งมั่น",
    nameEn: "Determination",
    symbol: Mountain,
    keywordTh: "ทะยานขึ้น",
    messageTh: "ยอดเขารอคนที่กล้าขึ้น จงปีนทีละก้าว ไม่ต้องมองสุดทาง ดูแค่ก้าวถัดไปก็พอ",
    affirmationTh: "ฉันมุ่งมั่นเดินขึ้นทีละก้าว",
    theme: "gold",
  },
];

export const ORACLE_SPREADS = [
  { id: "single", nameTh: "ไพ่ใบเดียว", nameEn: "Single Card", count: 1, cost: 5, descTh: "คำแนะนำสั้น ๆ จากจักรวาลสำหรับวันนี้" },
  { id: "three", nameTh: "สามใบ", nameEn: "Three Cards", count: 3, cost: 15, descTh: "ภาพกว้างขึ้น — สิ่งที่ควรรู้, สิ่งที่ควรทำ, สิ่งที่ควรมองข้าม" },
] as const;

export type OracleSpreadId = (typeof ORACLE_SPREADS)[number]["id"];

export function getOracleCard(id: number): OracleCard | undefined {
  return ORACLE_CARDS.find((c) => c.id === id);
}

export function drawOracleCards(count: number): OracleCard[] {
  const shuffled = [...ORACLE_CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, ORACLE_CARDS.length));
}
